### ISSUE TITLE
Use flask in project

### ISSUE THREAD

**Issue by wenta** [juliawenta/webMonster#1]
Add Flask and create simple endpoint (with healthcheck):
```python
@app.route("/healthcheck")
def health_check():
    return "Ok."
```

see http://flask.pocoo.org/docs/0.12/quickstart/

**Comment by abdulrahmanmazhar** [comment]
Hello, Do you mind asking what is this project about so maybe I can help a little bit with those issues? :smile:

**Comment by juliawenta** [comment]
Hi,
that's nice that you are asking but i am making this project in
collaboration with my brother :)
Have a nice day!
Julia

pt., 31.08.2018, 10:35 użytkownik Abdulrahman Mazhar <
notifications@github.com> napisał:

**Comment by abdulrahmanmazhar** [comment]
Aha that's very nice, Then wish for you both all success and fun as well, Thanks a lot for replying back 😊

**Comment by juliawenta** [comment]
I also want to learn Flask as well:)

**Comment by abdulrahmanmazhar** [comment]
Sure, Flask is a funny Framework to be working with and be building things on top of it as well, Wish all the success and luck for both of you 😊

**Comment by juliawenta** [comment]
Thanks!

31.08.2018 10:50 AM "Abdulrahman Mazhar" <notifications@github.com>
napisał(a):

Sure, Flask is a funny Framework to be working with and be building things
on top of it as well, Wish all the success and luck for both of you 😊

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/juliawenta/webMonster/issues/1#issuecomment-417598185>,
or mute the thread
